# Generated by Django 3.0.1 on 2019-12-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField()),
                ('meta', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('displayName', models.CharField(max_length=256)),
                ('breakable', models.BooleanField()),
                ('stack_type', models.PositiveSmallIntegerField(choices=[(1, 'non_stackable'), (16, 'special'), (64, 'stackable')], default=1)),
            ],
        ),
    ]
